#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math
import hashlib
from json import JSONDecodeError

DATA_SIZE = 1375


class Sender:
    def __init__(self, host, port):
        self.host = host
        self.remote_port = int(port)
        self.log("Sender starting up using port %s" % self.remote_port)
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))
        self.waiting = False
        self.packet_storage = {}
        self.tolerance = 1
        self.sequenceNumber = 0
        self.repeated_ack = 0
        self.timeout = 1.5

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def send(self, message):
        self.socket.sendto(json.dumps(message).encode('utf-8'), (self.host, self.remote_port))

    def run(self):
        while True:
            if self.tolerance > 32:
                self.tolerance = 32
            elif self.tolerance < 2:
                self.tolerance = 2
            sockets = [self.socket, sys.stdin] if not self.waiting else [self.socket]

            socks = select.select(sockets, [], [], 0.1)[0]
            time_out_flag = True
            packet_sent = 0;
            tolerance_flag = True
            for conn in socks:
                try:
                    if conn == self.socket:
                        k, addr = conn.recvfrom(65535)
                        msg = k.decode('utf-8')
                        msg = json.loads(msg)
                        temp_list = []
                        for x in self.packet_storage.keys():
                            temp_list.append(self.packet_storage[x][1])
                        if msg["Sequence"] not in temp_list:
                            raise ValueError
                        for x in list(self.packet_storage.keys()):
                            if self.packet_storage[x][1] == msg["Sequence"] and msg["type"] \
                                    == "ack" and msg["hash"] == \
                                    hashlib.shake_256(str(x).encode('utf-8')).hexdigest(3):
                                if (msg["time"] - self.packet_storage[x][0]) + \
                                        (float(str(time.time())[6:15]) - msg["time"]) \
                                        < self.timeout:
                                    self.tolerance *= 2
                                    self.timeout = math.ceil(self.timeout / 2)
                                self.packet_storage.pop(x, None)
                        self.log("Received message '%s'" % msg)
                        self.waiting = False
                    elif conn == sys.stdin:
                        tolerance_temp = self.tolerance
                        #The pakcages send but not acked still count in window
                        if len(self.packet_storage) >= 1:
                            tolerance_temp = self.tolerance - len(self.packet_storage)
                        for x in range(tolerance_temp):
                            data = sys.stdin.read(DATA_SIZE)
                            if len(data) == 0:
                                if self.packet_storage:
                                    continue
                                self.log("All done!")
                                sys.exit(0)
                            msg = {"type": "msg", "Sequence": self.sequenceNumber, "data": data,
                                   "hash": hashlib.shake_256(str(data).encode("utf-8")).hexdigest(3)}
                            # 0 in the array as being never retransmitted.
                            self.packet_storage[msg["data"]] = [float(str(time.time())[6:15]), self.sequenceNumber]
                            self.sequenceNumber += 1
                            self.log("Sending message '%s'" % msg)
                            packet_sent += 1
                            self.send(msg)
                            self.waiting = True
                except (NameError, JSONDecodeError, ValueError):
                    self.log("ooooooooooooooooooooooo")
                    self.repeated_ack += 1
                    if self.repeated_ack == 3:
                        self.tolerance = math.ceil(self.tolerance / 2)
                        self.repeated_ack = 0
                    continue
            loop_tolerance = self.tolerance - packet_sent
            if self.packet_storage is not None:
                for x in self.packet_storage.keys():
                    if loop_tolerance < 0:
                        break
                    # in packet_storage,key is data, 0 is time, 1 is sequence number
                    if float(str(time.time())[6:15]) - self.packet_storage[x][0] > self.timeout:
                        seq_temp = self.packet_storage[x][1]
                        msg = {"type": "msg", "Sequence": seq_temp, "data": x,
                               "hash": hashlib.shake_256(str(x).encode('utf-8')).hexdigest(3)}
                        self.send(msg)

                        self.log("Received message '%s'" % msg)
                        loop_tolerance -= 1
                        self.packet_storage[x][0] = float(str(time.time())[6:15])
                        if time_out_flag:
                            self.timeout *= 2
                            time_out_flag = False
                        if tolerance_flag:
                            self.tolerance = math.ceil(self.tolerance / 2)
                            tolerance_flag = False

        return


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data')
    parser.add_argument('host', type=str, help="Remote host to connect to")
    parser.add_argument('port', type=int, help="UDP port number to connect to")
    args = parser.parse_args()
    sender = Sender(args.host, args.port)
    sender.run()